function alpha = alpha_run(k1,k2,r,sa,si,theta,udes,z,zd)
%ALPHA_RUN
%    ALPHA = ALPHA_RUN(K1,K2,R,SA,SI,THETA,UDES,Z,ZD)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    02-Oct-2014 21:17:32

t2 = cos(theta);
t3 = sin(theta);
t4 = sa.^2;
t5 = si.^2;
t6 = t2.^2;
t7 = t5.*t6;
t8 = t3.^2;
t9 = t4.*t8;
t10 = t7+t9;
t13 = 1.0./t10;
t14 = t2.*t3.*t4.*2.0;
t15 = t2.*t3.*t5.*2.0;
t16 = t14-t15;
t17 = r.*t13.*t16;
t18 = 1.0./sqrt(t10);
t19 = 1.0./sa;
t20 = 1.0./si;
t21 = sqrt(t10);
t22 = r.*t19.*t20.*t21;
t23 = t22-1.0;
t24 = k1.*sa.*si.*t18.*t23;
t11 = t17+t24;
t30 = 1.0./zd;
t31 = t30.*z;
t12 = t31-1.0;
t25 = t11.^2;
t26 = r.^2;
t27 = t26.*4.0;
t28 = k2.^2;
t29 = zd.^2;
t32 = t12.^2;
t33 = t28.*t29.*t32;
t34 = t25+t27+t33;
alpha = sqrt(t34.*udes.^2)./t34;
