function v1 = v1_run(k1,k2,r,sa,si,theta,z,zd)
%V1_RUN
%    V1 = V1_RUN(K1,K2,R,SA,SI,THETA,Z,ZD)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    02-Oct-2014 21:17:32

t2 = cos(theta);
t3 = sin(theta);
t4 = sa.^2;
t5 = si.^2;
t6 = t2.^2;
t7 = t5.*t6;
t8 = t3.^2;
t9 = t4.*t8;
t10 = t7+t9;
v1 = [-(r.*(t2.*t3.*t4.*2.0-t2.*t3.*t5.*2.0))./t10-k1.*sa.*si.*1.0./sqrt(t10).*((r.*sqrt(t10))./(sa.*si)-1.0);r.*2.0;-k2.*zd.*(z./zd-1.0)];
